DROP TABLE MEMBER;

CREATE TABLE MEMBER(

	ID 				VARCHAR2(20) 	PRIMARY KEY,
	PW 			VARCHAR2(20) 	NOT NULL,
	NAME 		VARCHAR2(20) 	NOT NULL,
	EMAIL 		VARCHAR2(100) 	NOT NULL,
	PHONE 		VARCHAR2(11) 	NOT NULL,
	ADDR 		VARCHAR2(300) 	NOT NULL,
	ENABLED 	VARCHAR2(2) 	NOT NULL,
	BIRTH 		VARCHAR2(8) 	NOT NULL,
	REGDATE 	DATE 			NOT NULL,
	ROLE		VARCHAR2(20)	NOT NULL,
	
	CONSTRAINT CHECK_ENABLED CHECK(ENABLED IN('Y','N'))
);

INSERT INTO MEMBER VALUES('admin','0000','관리자','aaa@gmail.com','01000000000','서울시','Y','200121',SYSDATE,'ADMIN');
INSERT INTO MEMBER VALUES('user','0000','홍길동','bbb@gmail.com','01000000000','서울시','Y','990121',SYSDATE,'USER');

SELECT * FROM MEMBER;

----------------------------------------------------------------------------------------------------------------------

DROP SEQUENCE PRODUCTBOARDSEQ;
DROP TABLE PRODUCTBOARD;

CREATE SEQUENCE PRODUCTBOARDSEQ;
CREATE TABLE PRODUCTBOARD(
	PRODUCTBOARD_NO				NUMBER PRIMARY KEY,
	ID										VARCHAR2(20) NOT NULL,
	PRODUCTBOARD_TITLE			VARCHAR2(1000) NOT NULL,
	PRODUCTBOARD_CONTENT		VARCHAR2(3000) NOT NULL,
	PRODUCTBOARD_REGDATE		DATE NOT NULL,
	PRODUCTBOARD_READCOUNT	NUMBER NOT NULL,
	PRODUCTBOARD_STARSCORE	NUMBER NOT NULL,
	
	CONSTRAINT FK_PRODUCTBOARD_ID FOREIGN KEY(ID)
	REFERENCES MEMBER(ID)
);


SELECT * FROM PRODUCTBOARD ORDER BY PRODUCTBOARD_NO DESC;

INSERT INTO PRODUCTBOARD VALUES(PRODUCTBOARDSEQ.NEXTVAL,'her','채우기용','낚시ㅎㅎ',SYSDATE,0, 0);
INSERT INTO PRODUCTBOARD VALUES(PRODUCTBOARDSEQ.NEXTVAL,'her','채우기용','낚시ㅎㅎ',SYSDATE,0, 0);
INSERT INTO PRODUCTBOARD VALUES(PRODUCTBOARDSEQ.NEXTVAL,'user','채우기용','낚시ㅎㅎ',SYSDATE,0, 0);
INSERT INTO PRODUCTBOARD VALUES(PRODUCTBOARDSEQ.NEXTVAL,'user','채우기용','낚시ㅎㅎ',SYSDATE,0, 0);
INSERT INTO PRODUCTBOARD VALUES(PRODUCTBOARDSEQ.NEXTVAL,'user','채우기용','낚시ㅎㅎ',SYSDATE,0, 0);
INSERT INTO PRODUCTBOARD VALUES(PRODUCTBOARDSEQ.NEXTVAL,'user','채우기용','낚시ㅎㅎ',SYSDATE,0, 0);
INSERT INTO PRODUCTBOARD VALUES(PRODUCTBOARDSEQ.NEXTVAL,'user','채우기용','낚시ㅎㅎ',SYSDATE,0, 0);
INSERT INTO PRODUCTBOARD VALUES(PRODUCTBOARDSEQ.NEXTVAL,'user','채우기용','낚시ㅎㅎ',SYSDATE,0, 0);
